name: csi1000-v4
channels:
  - defaults
dependencies:
  - python=3.9.25
  - pip
  - pip:
      - lightgbm==4.6.0
      - numpy==2.0.2
      - pandas==2.3.3
      - scikit-learn==1.6.1
      - joblib==1.5.3
      - certifi==2026.5.20
      - streamlit==1.42.2
      - plotly==6.0.1
